/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ztq_sdk_jni_JniInterface */

#ifndef _Included_com_ztq_sdk_jni_JniInterface
#define _Included_com_ztq_sdk_jni_JniInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ztq_sdk_jni_JniInterface
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ztq_sdk_jni_JniInterface_get
  (JNIEnv *, jobject);

/*
 * Class:     com_ztq_sdk_jni_JniInterface
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ztq_sdk_jni_JniInterface_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
